# Informations sur le site
title: 👨‍🍳 Mon Carnet de Recettes
description: Recettes automatisées et testées.

# Choix du thème
theme: jekyll-theme-slate

# Configuration de la lecture (optionnel mais conseillé)
kramdown:
  input: GFM # Permet d'utiliser la syntaxe GitHub Flavored Markdown