[project]
name = "my-cookbook"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flake8>=7.3.0",
    "requests>=2.34.2",
]

[tool.uv.sources]
requests = { index = "jfrog" }
flake8 = { index = "jfrog" }

[[tool.uv.index]]
name = "jfrog"
url = "https://cochlear.jfrog.io/artifactory/api/pypi/coh-esw-pip/simple"
default = true
